import type { Metadata } from "next";
import { Lato, Quicksand } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

// Load Quicksand font with different weights (e.g., 300, 400, 700)
const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} ${lato.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
